version: '3'
services:
  adminer:
    container_name: adminer
    image: adminer:latest
    links:
      - db
    restart: always
    networks:
      - playground
#    depends_on:
#      - db
    ports:
      - "8081:8080"
  db:
    image: postgres:12-alpine
    restart: always
    container_name: db
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /db/playground_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: _eu~3d#4^nZ+c3V.
      POSTGRES_USER: playground
      POSTGRES_DB: playground_db
      PGDATA: pathtopgsqlData
    networks:
      - playground

networks:
  playground:
