name: Deploy

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '10.x'
    - run: |
        cd front
        npm install
        npm run lint
        npm install -g @angular/cli
        ng deploy --no-silent --repo=https://github.com/nicko466/myplayground.git --name="nicko446" --email=nicko466@gmail.com
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
